// gatsby-ssr.js
import React from 'react';

export const onRenderBody = ({ setHeadComponents }) => {
  setHeadComponents([
    <link
      key="proxima-black"
      rel="preload"
      href="/fonts/Proxima/proximanova-black.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-bold"
      rel="preload"
      href="/fonts/Proxima/proximanova-bold.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-extrabold"
      rel="preload"
      href="/fonts/Proxima/proximanova-extrabold.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-light"
      rel="preload"
      href="/fonts/Proxima/proximanova-light.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-medium"
      rel="preload"
      href="/fonts/Proxima/proximanova-medium.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-regular"
      rel="preload"
      href="/fonts/Proxima/proximanova-regular.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-semibold"
      rel="preload"
      href="/fonts/Proxima/proximanova-semibold.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    <link
      key="proxima-thin"
      rel="preload"
      href="/fonts/Proxima/proximanova-thin.otf"
      as="font"
      type="font/otf"
      crossOrigin="anonymous"
    />,
    
  ]);
};